#!/bin/bash
#=============================================================================
# genIVT_fit.sh - Generate i.MX6ULL HABv4 IVT (Image Vector Table) for FIT
#
# The HABv4 ROM authenticates images by locating the IVT at:
#     image_base + ALIGN(image_size, 0x1000)
#
# The IVT points to the CSF (Command Sequence File) which contains the
# actual signature data generated by NXP CST.
#
# Usage:
#     genIVT_fit.sh <fit_image> <load_addr> [ivt_output]
#
# Arguments:
#     fit_image   - Path to unsigned FIT .itb file
#     load_addr   - DDR load address in hex (e.g. 0x80800000)
#     ivt_output  - Output IVT binary path (default: ivt_fit.bin)
#
# Output (stdout):
#     IVT_OFFSET=<hex>    Offset within signed image where IVT starts
#     IVT_SIZE=0x20       Size of IVT (always 32 bytes)
#     SELF_ADDR=<hex>     Absolute DDR address of IVT
#     CSF_ADDR=<hex>      Absolute DDR address where CSF starts
#     CSF_OFFSET=<hex>    Offset within signed image where CSF starts
#
# IVT Layout (32 bytes, little-endian):
#     0x00: Tag        = 0x412000D1  (HABv4 header tag)
#     0x04: Entry      = load_addr   (image start in DDR)
#     0x08: Reserved1  = 0x00000000
#     0x0C: DCD        = 0x00000000  (no DCD for non-boot images)
#     0x10: Boot_Data  = 0x00000000
#     0x14: Self       = ivt_ddr_addr (IVT's own address)
#     0x18: CSF        = csf_ddr_addr (CSF address in DDR)
#     0x1C: Reserved2  = 0x00000000
#=============================================================================

set -e

readonly ALIGN_SIZE=0x1000
readonly IVT_SIZE=0x20

error() {
    echo "***" >&2
    echo " ERROR: ${1}" >&2
    echo "***" >&2
    exit 1
}

# --------------------------------------------------------------------------
# le32: Convert a 32-bit hex value to little-endian byte sequence
#       Input:  le32 0x412000D1
#       Output: D1 00 20 41 (raw bytes, space-separated hex digits)
# --------------------------------------------------------------------------
le32() {
    local val_hex
    val_hex=$(printf '%08x' "$1")
    # Reorder bytes: big-endian string → little-endian
    #   input:  AABBCCDD → output: DD CC BB AA
    printf '%s%s%s%s' \
        "${val_hex:6:2}" "${val_hex:4:2}" "${val_hex:2:2}" "${val_hex:0:2}"
}

# --------------------------------------------------------------------------
# Usage
# --------------------------------------------------------------------------
usage() {
    echo "Usage: $0 <fit_image> <load_addr> [ivt_output]"
    echo
    echo "  fit_image   Path to unsigned FIT .itb file"
    echo "  load_addr   DDR load address in hex (e.g. 0x80800000)"
    echo "  ivt_output  Output IVT binary path (default: ivt_fit.bin)"
    echo
    echo "Example:"
    echo "  $0 kernel_fit.itb 0x80800000 ivt_fit.bin"
    exit 1
}

# --------------------------------------------------------------------------
# Parse arguments
# --------------------------------------------------------------------------
FIT_IMAGE="${1}"
LOAD_ADDR="${2}"
IVT_OUTPUT="${3:-ivt_fit.bin}"

if [ -z "${FIT_IMAGE}" ] || [ -z "${LOAD_ADDR}" ]; then
    usage
fi

if [ ! -f "${FIT_IMAGE}" ]; then
    error "FIT image not found: ${FIT_IMAGE}"
fi

# --------------------------------------------------------------------------
# Calculate sizes and addresses
# --------------------------------------------------------------------------
# Get raw FIT image size (before padding/IVT/CSF)
# This is the size fit_get_size() returns at runtime in U-Boot
FIT_SIZE=$(stat -L -c%s "${FIT_IMAGE}")

# IVT offset = ALIGN(fit_size, 0x1000)
# This matches authenticate_image() in hab.c:
#   ivt_offset = (raw_image_size + ALIGN_SIZE - 1) & ~(ALIGN_SIZE - 1)
IVT_OFFSET=$(( (FIT_SIZE + ALIGN_SIZE - 1) & ~(ALIGN_SIZE - 1) ))

# Signed image total size up to end of IVT
#   bytes = ivt_offset + IVT_SIZE + CSF_PAD_SIZE  (in authenticate_image)
# The CSF follows immediately after IVT
CSF_OFFSET=$(( IVT_OFFSET + IVT_SIZE ))

# Absolute DDR addresses
LOAD_ADDR_NUM=$(printf '%d' "${LOAD_ADDR}")
SELF_ADDR=$(( LOAD_ADDR_NUM + IVT_OFFSET ))
CSF_ADDR=$(( LOAD_ADDR_NUM + CSF_OFFSET ))

# HABv4 IVT tag: 0x412000D1  (little-endian in memory)
IVT_TAG=0x412000D1

# DCD (Device Configuration Data) — not used for FIT images
DCD_ADDR=0x00000000
BOOT_DATA=0x00000000

# --------------------------------------------------------------------------
# Generate IVT binary (little-endian)
# --------------------------------------------------------------------------
{
    le32 ${IVT_TAG}      # 0x00: Tag = 0x412000D1
    le32 ${LOAD_ADDR_NUM} # 0x04: Entry (image load address)
    le32 0                # 0x08: Reserved1
    le32 ${DCD_ADDR}      # 0x0C: DCD pointer (unused for FIT)
    le32 ${BOOT_DATA}     # 0x10: Boot Data pointer (unused for FIT)
    le32 ${SELF_ADDR}     # 0x14: Self (IVT address in DDR)
    le32 ${CSF_ADDR}      # 0x18: CSF address in DDR
    le32 0                # 0x1C: Reserved2
} | xxd -r -p > "${IVT_OUTPUT}"

# Verify output size
IVT_ACTUAL_SIZE=$(stat -c%s "${IVT_OUTPUT}")
if [ "${IVT_ACTUAL_SIZE}" -ne "$((IVT_SIZE))" ]; then
    error "IVT size mismatch: expected ${IVT_SIZE}, got ${IVT_ACTUAL_SIZE}"
fi

# --------------------------------------------------------------------------
# Print parameters for downstream scripts (stdout, parseable)
# --------------------------------------------------------------------------
cat <<EOF
IVT_OFFSET=0x$(printf '%x' ${IVT_OFFSET})
IVT_SIZE=0x$(printf '%x' ${IVT_SIZE})
SELF_ADDR=0x$(printf '%x' ${SELF_ADDR})
CSF_ADDR=0x$(printf '%x' ${CSF_ADDR})
CSF_OFFSET=0x$(printf '%x' ${CSF_OFFSET})
FIT_SIZE=0x$(printf '%x' ${FIT_SIZE})
EOF

# Human-readable summary → stderr (NOT stdout!).
# stdout is consumed by mx6ull_sign_fit.sh via $() → eval,
# and any non-assignment text will crash the eval.
echo "" >&2
echo "IVT generated: ${IVT_OUTPUT} (${IVT_ACTUAL_SIZE} bytes)" >&2
echo "FIT raw size:  ${FIT_SIZE} bytes (0x$(printf '%x' ${FIT_SIZE}))" >&2
echo "IVT offset:    0x$(printf '%x' ${IVT_OFFSET})" >&2
echo "IVT DDR addr:  0x$(printf '%x' ${SELF_ADDR})" >&2
echo "CSF DDR addr:  0x$(printf '%x' ${CSF_ADDR})" >&2
