#!/bin/sh
### BEGIN INIT INFO
# Provides:          myir-enc
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Simple init script for myir-enc
# Description:       Run the encryption handler script
### END INIT INFO

SCRIPT="/usr/sbin/myir-enc.sh"
PIDFILE="/var/run/myir-enc.pid"
LOGFILE="/var/log/myir-enc.log"

check_running() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat $PIDFILE)" 2>/dev/null; then
        echo "Encryption handler script is already running."
        return 1
    fi
}

start() {
    echo "Starting encryption handler script..."
    check_running
    nohup "$SCRIPT" start >> "$LOGFILE" 2>&1 &
    echo $! > "$PIDFILE"
    echo "Started with PID $(cat $PIDFILE)"
}

stop() {
    echo "Stopping encryption handler script..."
    check_running
    nohup "$SCRIPT" stop >> "$LOGFILE" 2>&1
}

status() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat $PIDFILE)" 2>/dev/null; then
        echo "Running with PID $(cat $PIDFILE)"
    else
        echo "Not running"
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        ;;
esac

exit 0
