# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBMASK = "${LAYERDIR}/recipes-devtools"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
	    ${LAYERDIR/wic/*wks"

BBFILE_COLLECTIONS += "meta-swupdate-ad"
BBFILE_PATTERN_meta-swupdate-ad = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-swupdate-ad = "7"

LAYERDEPENDS_meta-swupdate-ad = "core"
LAYERDEPENDS_swupdate-imx = "openembedded-layer" 
LAYERSERIES_COMPAT_meta-swupdate-ad = "walnascar"
