#@TYPE: Machine
#@NAME: MYD-JMX95 15x15 Evaluation Kit with LPDDR5
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for NXP i.MX 95 15x15 EVK with LPDDR5
#@MAINTAINER: Mazel Li <Mazel.li@myir.cn>

MACHINEOVERRIDES =. "mx95:"

require conf/machine/include/myir-imx95.inc

MACHINE_FEATURES:append:use-nxp-bsp = " nxp8997-sdio"

IMX_KERNEL_CONFIG_AARCH64 = "myd_jmx95_15x15_defconfig"

KERNEL_DEVICETREE_BASENAME = "myd-jmx95-15x15"

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    myir/myd-jmx95-15x15.dtb \
    myir/myd-jmx95-15x15-lvds-dual.dtb \
    myir/myd-jmx95-15x15-dsi-mipi101c.dtb \
    myir/myd-jmx95-15x15-lvds0-lvds1-ov5640.dtb \
    myir/myd-jmx95-15x15-lt9611-lvds1-ov5640.dtb \
    myir/myd-jmx95-15x15-4k-lt9611-lvds1-ov5640.dtb \
"

UBOOT_CONFIG_BASENAME = "myd_jmx95_15x15"

IMXBOOT_TARGETS_BASENAME = "flash"

OEI_BOARD  = "mx95lp5-4g-15"
DDR_TYPE   = "lpddr5"
DDR_FIRMWARE_NAME = " \
    lpddr5_dmem_v202409.bin \
    lpddr5_dmem_qb_v202409.bin \
    lpddr5_imem_v202409.bin \
    lpddr5_imem_qb_v202409.bin \
"
OEI_DDR_CONFIG     = "MIMX95_LPDDR5_EVK_15X15_4266MTS_FW2024.09_timing"
OEI_DDR_CONFIG_ECC = "MIMX95_LPDDR5_EVK_15X15_4266MTS_FW2024.09_ECC_enabled_timing"

M4_DEFAULT_IMAGE_MX95 = "imx95-15x15-evk_m7_TCM_power_mode_switch.bin"

IMAGE_BOOT_FILES:append = " \
    mcore-demos/imx95-15x15-evk_m7_TCM_power_mode_switch.bin \
    mcore-demos/imx95-15x15-evk_m7_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    mcore-demos/imx95-15x15-evk_m7_TCM_rpmsg_lite_str_echo_rtos.bin \
    mcore-demos/imx95-15x15-evk_m7_TCM_sai_low_power_audio.bin \
"
# Set time zone
DEFAULT_TIMEZONE = "Asia/Shanghai"
