
require include/myir-imx93-evk.inc

KERNEL_DEVICETREE_BASENAME = "myd-imx93-11x11"

KERNEL_DEVICETREE:append:use-nxp-bsp = " \
    myir/${KERNEL_DEVICETREE_BASENAME}-rgb.dtb \
 "


UBOOT_DTB_NAME = "myd-lmx93x-11x11"
UBOOT_CONFIG ??= "sd_1g"


DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"

WKS_FILE_DEPENDS:append:imx-nxp-bsp = " imx-m33-demos"
IMAGE_BOOT_FILES:append:imx-nxp-bsp = " \
    mcore-demos/imx93-11x11-evk_m33_TCM_low_power_wakeword.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_power_mode_switch.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_rpmsg_lite_str_echo_rtos.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_sai_low_power_audio.bin \
"

