
require include/myir-lmx9x-evk.inc



KERNEL_DEVICETREE_BASENAME = "myd-lmx9x-11x11"
IMX_KERNEL_CONFIG_AARCH64 = "${KERNEL_DEVICETREE_BASENAME}_defconfig"
KERNEL_DEVICETREE:append:use-nxp-bsp = " \
 		myir/${KERNEL_DEVICETREE_BASENAME}.dtb \
		myir/${KERNEL_DEVICETREE_BASENAME}-lvds.dtb \
    myir/${KERNEL_DEVICETREE_BASENAME}-rgb.dtb \
 "

UBOOT_DTB_NAME = "${KERNEL_DEVICETREE_BASENAME}.dtb"
UBOOT_CONFIG ??= "sd_1g"


UBOOT_CONFIG[sd_1g]      = "${KERNEL_DEVICETREE_BASENAME}_1g_defconfig,sdcard"
UBOOT_CONFIG[sd_2g]      = "${KERNEL_DEVICETREE_BASENAME}_2g_defconfig,sdcard"

DDR_FIRMWARE_NAME = " \
    lpddr4_dmem_1d_v202201.bin \
    lpddr4_dmem_2d_v202201.bin \
    lpddr4_imem_1d_v202201.bin \
    lpddr4_imem_2d_v202201.bin \
"

WKS_FILE_DEPENDS:append:imx-nxp-bsp = " imx-m33-demos"
IMAGE_BOOT_FILES:append:imx-nxp-bsp = " \
    mcore-demos/imx93-11x11-evk_m33_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_rpmsg_lite_str_echo_rtos.bin \
    mcore-demos/imx93-11x11-evk_m33_TCM_sai_low_power_audio.bin \
"

