#!/bin/sh -x

mdev="/dev/media0"
mediactl="media-ctl -d $mdev"
cam="ov5640 0-003c"
csi="csidev-4ae00000.csi"
isi="mxc_isi.0"
code="UYVY8_1X16"
fmt="YUYV"
width="1280"
height="720"
format="fmt:${code}/${width}x${height} field:none"

$mediactl -r

$mediactl -l "\"$cam\":0 -> \"$csi\":0 [1]"
$mediactl -V "\"$cam\":0 [$format]"
$mediactl -V "\"$csi\":0/0 [$format]"
$mediactl -V "\"crossbar\":0 [$format]"
$mediactl -V "\"$isi\":0 [$format]"

gst-launch-1.0 -e v4l2src device=/dev/video0 io-mode=2 num-buffers=10 ! video/x-raw,format=YUY2,width=1280,height=720 ! videoconvert ! jpegenc ! multifilesink location=pic.jpg max-files=1