#!/bin/bash
#=============================================================================
# gen_fuse_cmds.sh - Generate i.MX95 AHAB Fuse Burning Commands
#
# This script reads the SRK fuse file generated by NXP CST srktool and
# generates U-Boot fuse commands for burning the SRK hash into the
# i.MX95's one-time programmable (OTP) eFuses.
#
# WARNING: Fuse burning is IRREVERSIBLE! Each fuse bit can only be
# programmed from 0 to 1, never back to 0. Once the SRK fuses are
# burned and the device is closed (ahab_close), only images signed
# with the corresponding SRK private key will boot.
#
# Prerequisites:
#   - SRK fuse file: ${CST_DIR}/crts/SRK_1_2_3_4_fuses.bin
#   - U-Boot console access to the target device
#
# Usage:
#   ./gen_fuse_cmds.sh                    # Generate U-Boot fuse commands
#   ./gen_fuse_cmds.sh --nxpele           # Generate nxpele commands (SPSDK)
#   ./gen_fuse_cmds.sh --verify           # Generate verification commands
#
# Fuse burning procedure (in U-Boot):
#   1. Boot the device into U-Boot (unsigned image still works before close)
#   2. Paste and run each fuse command one by one
#   3. Verify fuses with the verification commands
#   4. Run 'ahab_close' to close the device
#   5. After close, only signed images will boot
#
# Reference:
#   i.MX95 Reference Manual - Fusemap chapter
#   i.MX95 Security Reference Manual - AHAB section
#=============================================================================

set -e

CST_DIR="${CST_DIR:-${HOME}/cst}"
SRK_FUSE_FILE="${CST_DIR}/crts/SRK_1_2_3_4_fuses.bin"

# i.MX95 OTP fuse word indices for SRK hash
# These map the SRK table hash into specific OTP fuse words.
# The SRK hash (SHA-384 = 384 bits = 12 x 32-bit words) is stored
# in consecutive OTP fuse words starting from SRK_FUSE_BASE.
#
# WARNING: These indices may vary by silicon revision.
# Always verify against the i.MX95 Reference Manual Fusemap.
SRK_FUSE_BASE=800     # Base fuse word for SRK hash (example - verify with RM!)

echo "============================================"
echo "i.MX95 AHAB Fuse Command Generator"
echo "============================================"

if [ ! -f "${SRK_FUSE_FILE}" ]; then
    echo "ERROR: SRK fuse file not found: ${SRK_FUSE_FILE}"
    echo "Please run gen_keys.sh first to generate the SRK keys."
    exit 1
fi

echo "SRK Fuse File: ${SRK_FUSE_FILE}"
echo "SRK Fuse Base Word: ${SRK_FUSE_BASE}"
echo ""

# Read the SRK fuse file and convert to 32-bit words
# The srktool generates the fuse file with the SRK hash values
SRK_FUSE_SIZE=$(stat -c%s "${SRK_FUSE_FILE}" 2>/dev/null || stat -f%z "${SRK_FUSE_FILE}")
echo "SRK fuse file size: ${SRK_FUSE_SIZE} bytes"

echo ""
echo "============================================"
echo "FUSE BURNING COMMANDS (U-Boot Console)"
echo "============================================"
echo ""
echo "# --- IMPORTANT SAFETY NOTES ---"
echo "# 1. Fuse burning is IRREVERSIBLE"
echo "# 2. Test with unsigned images FIRST to verify U-Boot works"
echo "# 3. Burn fuses one at a time, verify after each"
echo "# 4. Keep the private keys safe - without them, the device is bricked"
echo "# 5. Do NOT close the device until ALL fuses are verified"
echo ""

# Generate U-Boot fuse commands
echo "# --- SRK Hash Fuses ---"
echo "# Burn the SRK public key hash into OTP fuses"
echo ""

# Read the fuse file as hex and generate per-word commands
# The format from srktool is typically:
#   For each byte/word in the SRK hash, generate: fuse prog <addr> <value>
OD=$(which od 2>/dev/null || which hexdump 2>/dev/null)

if [ -n "${OD}" ]; then
    # Use od to read as 32-bit big-endian words
    WORD_INDEX=0
    while IFS= read -r line; do
        if [ -n "${line}" ]; then
            WORD_ADDR=$((SRK_FUSE_BASE + WORD_INDEX))
            printf "fuse prog %d 0x%s       # SRK hash word %d\n" \
                "${WORD_ADDR}" "${line}" "${WORD_INDEX}"
            WORD_INDEX=$((WORD_INDEX + 1))
        fi
    done < <(od -A n -t x4 -v "${SRK_FUSE_FILE}")
else
    # Fallback: generate generic instructions
    echo "# (od/hexdump not available - using generic format)"
    echo "# SRK hash data from: ${SRK_FUSE_FILE}"
    echo ""
    xxd -g 4 "${SRK_FUSE_FILE}" | while read -r offset hex ascii; do
        for word in ${hex}; do
            WORD_ADDR=$((SRK_FUSE_BASE + offset / 4))
            echo "fuse prog ${WORD_ADDR} 0x${word}"
            break  # Take first word per line
        done
    done
fi

echo ""
echo "# --- SRK Lock Fuse ---"
echo "# Lock the SRK region to prevent further programming"
echo "fuse prog ${SRK_FUSE_BASE} 0x1    # (check actual lock bit in RM)"

echo ""
echo "# --- Lifecycle Close ---"
echo "# Close the device to enforce secure boot"
echo "# WARNING: This is the final irreversible step!"
echo "# u-boot=> ahab_close"
echo ""

echo ""
echo "============================================"
echo "FUSE VERIFICATION COMMANDS (U-Boot Console)"
echo "============================================"
echo ""

# Generate verification commands
echo "# Verify each SRK fuse word was programmed correctly"
echo ""
WORD_INDEX=0
while IFS= read -r line; do
    if [ -n "${line}" ]; then
        WORD_ADDR=$((SRK_FUSE_BASE + WORD_INDEX))
        echo "# fuse read ${WORD_ADDR}    # Expected: 0x${line}"
        WORD_INDEX=$((WORD_INDEX + 1))
    fi
done < <(od -A n -t x4 -v "${SRK_FUSE_FILE}" 2>/dev/null || echo "")

if [ ${WORD_INDEX} -eq 0 ]; then
    echo "# (Could not parse fuse file - manually verify from file content)"
    echo "# hexdump -C ${SRK_FUSE_FILE}"
fi

echo ""
echo "# --- Verification Summary Commands ---"
echo "# Check device security state:"
echo "# u-boot=> ahab_status"
echo ""
echo "# Read full SRK fuse region:"
echo "# u-boot=> fuse read ${SRK_FUSE_BASE} ${WORD_INDEX}"
echo ""

echo ""
echo "============================================"
echo "COMPLETE FUSE BURNING PROCEDURE"
echo "============================================"
echo ""
echo "Step 1: Boot unsigned image on target device"
echo "  -> U-Boot prompt should appear"
echo ""
echo "Step 2: Burn SRK hash fuses (copy-paste each command above)"
echo "  u-boot=> fuse prog <addr> <value>"
echo ""
echo "Step 3: Verify fuses"
echo "  u-boot=> fuse read <addr> <count>"
echo "  Compare with values from the verification section above"
echo ""
echo "Step 4: Lock SRK region (if applicable - check RM)"
echo "  u-boot=> fuse prog <lock_addr> <lock_value>"
echo ""
echo "Step 5: Close the device"
echo "  u-boot=> ahab_close"
echo "  WARNING: After this, only images signed with your SRK will boot!"
echo ""
echo "Step 6: Power cycle and verify secure boot"
echo "  - Device should boot ONLY signed images"
echo "  - Unsigned images should fail with AHAB authentication error"
echo ""
echo "============================================"
echo "WARNING: Test in development environment first!"
echo "Have a backup plan for recovery if something goes wrong."
echo "============================================"

# Optional: Generate nxpele commands if SPSDK is available
if [ "$1" == "--nxpele" ]; then
    echo ""
    echo "============================================"
    echo "ALTERNATIVE: nxpele (SPSDK) Commands"
    echo "============================================"
    echo ""
    echo "# If using SPSDK nxpele tool instead of U-Boot console:"
    echo "# Install: pip install spsdk"
    echo ""

    echo "# Write SRK fuses:"
    od -A n -t x4 -v "${SRK_FUSE_FILE}" 2>/dev/null | while IFS= read -r line; do
        if [ -n "${line}" ]; then
            echo "nxpele write-fuse --index ${WORD_ADDR} --data 0x${line}"
        fi
    done

    echo ""
    echo "# Close device:"
    echo "nxpele ahab-close"
    echo ""
fi
