# myir-ahab.bbclass - AHAB Secure Boot Signing for i.MX9 (i.MX93/i.MX95)
#
# Based on the NXP AHAB secure boot bbclass pattern.
# Provides AHAB (Advanced High Assurance Boot) signing support for i.MX9
# processors using NXP's CST (Code Signing Tool).
#
# For i.MX95, the ELE (EdgeLock Enclave) uses AHAB container format.
# Signing requires:
#   - ECC secp384r1 keys (minimum for i.MX95)
#   - AHAB CSF template with proper container offsets
#   - NXP CST tool (v3.3.0+ for i.MX9 support)
#
# Usage in local.conf:
#   MYIR_AHAB_ENABLE = "1"
#   MYIR_AHAB_CST_DIR = "${TOPDIR}/keys/cst"
#
# Reference: NXP AHAB documentation


# ==========================================================================
# Enable/Disable AHAB signing
# ==========================================================================
MYIR_AHAB_ENABLE ?= "0"

# ==========================================================================
# NXP CST Tool paths
# ==========================================================================

# Root directory of CST tool installation
MYIR_AHAB_CST_DIR ?= "${TOPDIR}/keys/cst"

# Build CST from source (1) or use prebuilt (0)
MYIR_AHAB_CST_BUILD_FROM_SOURCE ?= "0"

# CST binary path
MYIR_AHAB_CST_BIN ?= "${@ '${RECIPE_SYSROOT_NATIVE}/usr/bin/cst'                         if d.getVar('MYIR_AHAB_CST_BUILD_FROM_SOURCE') == '1'                         else '${MYIR_AHAB_CST_DIR}/linux64/bin/cst' }"

# Additional parameters to pass to CST tool (e.g. -v for verbose)
MYIR_AHAB_CST_ARGS ?= ""

# ==========================================================================
# Cryptographic key parameters
# ==========================================================================

# Key type: "ecc" or "rsa"
MYIR_AHAB_CST_CRYPTO    ?= "ecc"

# ECC curve (i.MX95 minimum: secp384r1)
# For RSA, this would be key length in bits (e.g. "2048", "4096")
MYIR_AHAB_CST_KEY_CURVE ?= "secp384r1"

# Digest algorithm
MYIR_AHAB_CST_DIG_ALGO  ?= "sha384"

# Whether SRK certificate has CA flag set (1=CA, 0=user/non-CA)
# CA flag allows subordinate keys (SGK), but SGK is NOT supported
# on i.MX9 ELE firmware as of April 2025.
MYIR_AHAB_CST_SRK_CA    ?= "0"

# SRK index to use for signing (1..4, maps to SRK1..SRK4)
MYIR_AHAB_CST_SRK_INDEX ?= "1"
MYIR_AHAB_CST_SRK_SOURCE_IDX ?= "${@myir_ahab_srk_source_idx(d)}"

# ==========================================================================
# Directories for certificates and keys
# ==========================================================================

# Directory containing certificate PEM files
MYIR_AHAB_CST_CERTS_DIR ?= "${MYIR_AHAB_CST_DIR}/crts"

# Directory containing private key PEM files
MYIR_AHAB_CST_KEYS_DIR  ?= "${MYIR_AHAB_CST_DIR}/keys"

# ==========================================================================
# SRK table and fuse files
# ==========================================================================

# SRK table binary (generated by srktool, contains hash of all 4 SRKs)
MYIR_AHAB_CST_SRK       ?= "${MYIR_AHAB_CST_CERTS_DIR}/SRK_1_2_3_4_tables.bin"

# SRK fuse values (for burning into OTP eFuses)
MYIR_AHAB_CST_SRK_FUSE  ?= "${MYIR_AHAB_CST_CERTS_DIR}/SRK_1_2_3_4_fuses.bin"

# ==========================================================================
# Certificate file names (auto-generated based on key parameters)
# ==========================================================================

# SRK certificate PEM
MYIR_AHAB_CST_SRK_CERT  ?= "${@make_myir_srk_cert_name(d)}"

# SGK certificate PEM (only used when SRK_CA=1 and SGK_SUPP=1)
MYIR_AHAB_CST_SGK_CERT  ?= "${@make_myir_sgk_cert_name(d)}"

# Whether SGK (subordinate key) is supported by SoC firmware
# i.MX9 ELE firmware (as of April 2025) does NOT support SGK
MYIR_AHAB_CST_SGK_SUPP  ?= "0"

# Name of the AHAB CSF template file
# Must be set in the recipe that does the signing
MYIR_AHAB_CSF_TEMPLATE  ?= "mx95_ahab.csf.template"

# ==========================================================================
# Helper functions for certificate name generation
# ==========================================================================

def make_myir_srk_cert_name(d):
    """Generate SRK certificate filename based on key parameters."""
    import os
    idx = d.getVar('MYIR_AHAB_CST_SRK_INDEX')
    dalgo = d.getVar('MYIR_AHAB_CST_DIG_ALGO')
    curve = d.getVar('MYIR_AHAB_CST_KEY_CURVE')
    ca = int(d.getVar('MYIR_AHAB_CST_SRK_CA'))
    castr = 'ca' if ca != 0 else 'usr'
    basedir = d.getVar('MYIR_AHAB_CST_CERTS_DIR')
    return os.path.join(basedir, f'SRK{idx}_{dalgo}_{curve}_v3_{castr}_crt.pem')

def make_myir_sgk_cert_name(d):
    """Generate SGK certificate filename based on key parameters."""
    import os
    idx = d.getVar('MYIR_AHAB_CST_SRK_INDEX')
    dalgo = d.getVar('MYIR_AHAB_CST_DIG_ALGO')
    curve = d.getVar('MYIR_AHAB_CST_KEY_CURVE')
    basedir = d.getVar('MYIR_AHAB_CST_CERTS_DIR')
    return os.path.join(basedir, f'SGK{idx}_1_{dalgo}_{curve}_v3_usr_crt.pem')

def myir_ahab_srk_source_idx(d):
    """Convert 1-based SRK_INDEX to 0-based source index for CSF."""
    idx = int(d.getVar('MYIR_AHAB_CST_SRK_INDEX'))
    if idx < 1 or idx > 4:
        bb.fatal('MYIR_AHAB_CST_SRK_INDEX must be in range [1,4]')
    return str(idx - 1)

# ==========================================================================
# AHAB container offsets (for flash.bin / kernel container signing)
# These are extracted from mkimage output at build time.
# The values below are fallback defaults.
# ==========================================================================

# Container header offset in the AHAB container
MYIR_AHAB_CONTAINER_HEADER_OFFSET ?= '0x0'

# Signature block offset in the AHAB container
MYIR_AHAB_SIGNATURE_BLOCK_OFFSET ?= '0x110'
