# myir-hab.bbclass - HABv4 Secure Boot Signing (i.MX6/i.MX7/i.MX8M)
#
# Provides HABv4 (High Assurance Boot v4) signing support for i.MX6/7/8M
# processors using NXP's CST (Code Signing Tool).
#
# For i.MX6ULL (Cortex-A7, no CAAM), HABv4 uses:
#   - RSA 2048/4096 keys (default: 2048)
#   - Software engine (Engine = SW), no CAAM acceleration
#   - CSF binary concatenated to u-boot.imx (not AHAB container)
#   - SPL is signed separately with its own CSF
#
# This class runs in PARALLEL with myir-ahab.bbclass and is mutually
# exclusive at the machine level via mx6ull-generic-bsp vs mx9-generic-bsp
# overrides.

# ==========================================================================
# Enable/Disable HAB signing (master switch)
# ==========================================================================
MYIR_HAB_ENABLE ?= "0"

# ==========================================================================
# NXP CST Tool (shared with AHAB, but HAB may use different binary path)
# ==========================================================================

# Root directory of CST tool installation
MYIR_HAB_CST_DIR ?= "${TOPDIR}/keys/cst"

# Build CST from source (1) or use prebuilt (0)
MYIR_HAB_CST_BUILD_FROM_SOURCE ?= "0"

# CST binary path (same binary, different usage mode)
MYIR_HAB_CST_BIN ?= "${@ '${RECIPE_SYSROOT_NATIVE}/usr/bin/cst' \
                        if d.getVar('MYIR_HAB_CST_BUILD_FROM_SOURCE') == '1' \
                        else '${MYIR_HAB_CST_DIR}/linux64/bin/cst' }"

# Additional parameters to pass to CST tool (e.g. -v for verbose)
MYIR_HAB_CST_ARGS ?= ""

# ==========================================================================
# Cryptographic key parameters (RSA for HABv4 on i.MX6/7)
#
# i.MX6ULL HABv4 default: RSA 2048-bit, SHA-256 digest
# CA flag is typically set for HABv4 to allow CSF/IMG subordinate keys
# ==========================================================================

# Key type: "rsa" (HABv4 uses RSA; ECC is AHAB-only)
MYIR_HAB_CST_CRYPTO    ?= "rsa"

# Key size in bits (2048 or 4096)
MYIR_HAB_CST_KEY_SIZE  ?= "2048"

# Key exponent for RSA
MYIR_HAB_CST_KEY_EXP   ?= "65537"

# Digest algorithm
MYIR_HAB_CST_DIG_ALGO  ?= "sha256"

# Whether SRK certificate has CA flag set (1=CA, 0=user/non-CA)
# HABv4 traditionally uses CA=1 to enable CSF/IMG subordinate keys
MYIR_HAB_CST_SRK_CA    ?= "1"

# SRK index to use for signing (1..4, maps to SRK1..SRK4)
MYIR_HAB_CST_SRK_INDEX ?= "1"

# ==========================================================================
# Directories for certificates and keys (separate from AHAB)
# Default: TOPDIR/keys/cst (shared CST directory)
# ==========================================================================

MYIR_HAB_CST_CERTS_DIR ?= "${MYIR_HAB_CST_DIR}/crts"
MYIR_HAB_CST_KEYS_DIR  ?= "${MYIR_HAB_CST_DIR}/keys"

# ==========================================================================
# SRK table and fuse files
# ==========================================================================

# SRK table binary (generated by srktool, contains hash of all 4 SRKs)
MYIR_HAB_CST_SRK       ?= "${MYIR_HAB_CST_CERTS_DIR}/SRK_1_2_3_4_table.bin"

# SRK fuse values (for burning into OTP eFuses)
MYIR_HAB_CST_SRK_FUSE  ?= "${MYIR_HAB_CST_CERTS_DIR}/SRK_1_2_3_4_fuse.bin"

# ==========================================================================
# Certificate file names (auto-generated based on key parameters)
# ==========================================================================

# SRK certificate PEM
MYIR_HAB_CST_SRK_CERT  ?= "${@make_myir_hab_srk_cert_name(d)}"

# CSF certificate PEM (only used when SRK_CA=1)
MYIR_HAB_CST_CSF_CERT  ?= "${@make_myir_hab_sub_cert_name(d, 'CSF')}"

# IMG certificate PEM (only used when SRK_CA=1)
MYIR_HAB_CST_IMG_CERT  ?= "${@make_myir_hab_sub_cert_name(d, 'IMG')}"

# ==========================================================================
# SDP loading support (i.MX6ULL specific)
# ==========================================================================

# List of U-Boot configurations targeting SDP loading
# "*" means all configurations; normally a subset of UBOOT_CONFIG
MYIR_HAB_SDP_CONFIGS ?= ""

# Internal version: only active on i.MX6ULL/7 where SDP is relevant
MYIR_HAB_SDP_CONFIGS_INTERNAL:mx6ull-generic-bsp = "${MYIR_HAB_SDP_CONFIGS}"
MYIR_HAB_SDP_CONFIGS_INTERNAL:mx7-generic-bsp    = "${MYIR_HAB_SDP_CONFIGS}"

# ==========================================================================
# Helper functions for certificate name generation
# ==========================================================================

def make_myir_hab_srk_cert_name(d):
    """Generate SRK certificate filename based on key parameters."""
    import os
    kidx = int(d.getVar('MYIR_HAB_CST_SRK_INDEX'))
    crypto = d.getVar('MYIR_HAB_CST_CRYPTO')
    dalgo = d.getVar('MYIR_HAB_CST_DIG_ALGO')
    ksize = d.getVar('MYIR_HAB_CST_KEY_SIZE')
    ca = int(d.getVar('MYIR_HAB_CST_SRK_CA'))
    castr = 'ca' if ca != 0 else 'usr'
    basedir = d.getVar('MYIR_HAB_CST_CERTS_DIR')
    if kidx < 1 or kidx > 4:
        bb.fatal('MYIR_HAB_CST_SRK_INDEX must be in range [1,4]')
    if crypto == 'rsa':
        kexp = d.getVar('MYIR_HAB_CST_KEY_EXP')
        return os.path.join(basedir, f'SRK{kidx}_{dalgo}_{ksize}_{kexp}_v3_{castr}_crt.pem')
    else:
        bb.fatal('MYIR_HAB_CST_CRYPTO must be "rsa" for HABv4')
    return ''

def make_myir_hab_sub_cert_name(d, prefix):
    """Generate subordinate certificate name (CSF/IMG)."""
    import os
    kidx = int(d.getVar('MYIR_HAB_CST_SRK_INDEX'))
    crypto = d.getVar('MYIR_HAB_CST_CRYPTO')
    dalgo = d.getVar('MYIR_HAB_CST_DIG_ALGO')
    ksize = d.getVar('MYIR_HAB_CST_KEY_SIZE')
    ca = int(d.getVar('MYIR_HAB_CST_SRK_CA'))
    basedir = d.getVar('MYIR_HAB_CST_CERTS_DIR')
    if kidx < 1 or kidx > 4:
        bb.fatal('MYIR_HAB_CST_SRK_INDEX must be in range [1,4]')
    if ca == 0:
        return ''
    if crypto == 'rsa':
        kexp = d.getVar('MYIR_HAB_CST_KEY_EXP')
        return os.path.join(basedir, f'{prefix}{kidx}_1_{dalgo}_{ksize}_{kexp}_v3_usr_crt.pem')
    return ''

def myir_hab_srk_source_idx(d):
    """Convert 1-based SRK_INDEX to 0-based source index for CSF."""
    idx = int(d.getVar('MYIR_HAB_CST_SRK_INDEX'))
    if idx < 1 or idx > 4:
        bb.fatal('MYIR_HAB_CST_SRK_INDEX must be in range [1,4]')
    return str(idx - 1)
